modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"
issueTrackerURL = "https://github.com/TheLMiffy1111/PackagedExCrafting/issues"

[[mods]]
	modId = "packagedexcrafting"
	version = "0@VERSION@"
	displayName = "PackagedExCrafting"
	description = "A PackagedAuto addon that adds ExtendedCrafting autocrafting."
	logoFile = "packagedexcrafting.logo.png"
	authors = "TheLMiffy1111"
	displayURL = "https://www.curseforge.com/minecraft/mc-mods/packagedexcrafting"

[[dependencies.packagedexcrafting]]
	modId = "neoforge"
	versionRange = "[21,)"
	type = "required"

[[dependencies.packagedexcrafting]]
	modId = "packagedauto"
	versionRange = "[4,)"
	type = "required"

[[dependencies.packagedexcrafting]]
	modId = "extendedcrafting"
	versionRange = "[7,)"
	type = "required"
